-- BUG-ESOCIAL-05 (#455)
--
-- Migration intencionalmente vazia. O conteudo original era byte-identico ao
-- de 79.sql e tentava adicionar novamente as mesmas duas colunas. O arquivo e
-- preservado para nao quebrar a sequencia historica das migrations; 79.sql e
-- a fonte canonica de processamentos_folha.esocial_status e
-- processamentos_folha.esocial_fechado_em.
