-- BUG-ESOCIAL-05 (#455)
--
-- Migration intencionalmente vazia. A trigger original nao representava o
-- schema real:
--   - a coluna de status e eventos_esocial.status, cujos valores nao incluem
--     "fechado";
--   - eventos_esocial nao possui processamento_folha_id nem outro vinculo com
--     processamentos_folha.
--
-- Trocar apenas NEW.eventos_esocial_status por NEW.status manteria a trigger
-- incorreta e ainda quebraria ao acessar NEW.processamento_folha_id. O
-- fechamento mensal (S-1299) precisa de modelagem propria quando o Grupo 4 for
-- implementado. A migration 85.sql continua removendo a funcao/trigger legada
-- em bancos que tenham executado a versao antiga desta migration.
